### KPI Analysis - Sales Analytics Dashboard

## Objectives
Creat key business metrics (KPIs) to support dashboard development and decision_making.

## KPI focus
- Revenue performance
- Profitability
- Order behaviour
- Product and regional performance

In [33]:
import pandas as pd
import matplotlib.pyplot as plt

df = pd.read_csv("../data/processed/clean_superstore.csv")
df.head()

,row_id,order_id,order_date,ship_date,ship_mode,customer_id,customer_name,segment,country,city,...,postal_code,region,product_id,category,sub_category,product_name,sales,quantity,discount,profit
0,1,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136
1,2,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820
2,3,CA-2016-138688,2016-06-12,2016-06-16,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,90036,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714
3,4,US-2015-108966,2015-10-11,2015-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310
4,5,US-2015-108966,2015-10-11,2015-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164

In [34]:
df['order_date'] = pd.to_datetime(df['order_date'])
df['ship_date'] = pd.to_datetime(df['ship_date'])

In [35]:
df['year'] = df['order_date'].dt.year
df['month'] = df['order_date'].dt.month
df['month_name'] = df['order_date'].dt.strftime('%b')

In [36]:
total_sales =df['sales'].sum()
total_profit = df['profit'].sum()
total_orders = df['order_id'].nunique()
total_quantity = df['quantity'].sum()

print("Total Sales:", total_sales)
print("Total Profit:" , total_profit)
print("Total Orders:" , total_orders)
print("Total Quantity:", total_quantity)

Total Sales: 2297200.8603
Total Profit: 286397.0217
Total Orders: 5009
Total Quantity: 37873

### Core KPIs

These metrics provide a high-level view of business performance:
- Total Sales reflects overall revenue
- Tota Profit indicates profitability
- Total Orders shows transaction volume
- Total Quantity reflects units sold

In [37]:
df['profit_margin'] = df['profit']/df['sales']

avg_profit_margin =df['profit_margin'].mean()

avg_profit_margin

np.float64(0.12031392972104457)

### Profit Margin

Profit margin measures how efficiently revenue is converted into profit.

Lower margins may indicate high costs or excessive discounting.

In [38]:
aov = df.groupby('order_id')['sales'].sum().mean()

aov

np.float64(458.61466566180883)

### Average Order Value

AOV represents teh average revenue per transaction.

This helps understand customer purchasing behaviour.

In [39]:
monthly_kpis = df.groupby(pd.Grouper(key='order_date' , freq='M')).agg({
    'sales':'sum',
'profit':'sum',
'order_id':'nunique'
    }).reset_index()

monthly_kpis.rename(columns={'order_id':'orders'},inplace=True)
monthly_kpis.head()

C:\Users\Cahil\AppData\Local\Temp\ipykernel_11672\2042300878.py:1: FutureWarning: 'M' is deprecated and will be removed in a future version, please use 'ME' instead.
  monthly_kpis = df.groupby(pd.Grouper(key='order_date' , freq='M')).agg({

  order_date      sales     profit  orders
0 2014-01-31  14236.895  2450.1907      32
1 2014-02-28   4519.892   862.3084      28
2 2014-03-31  55691.009   498.7299      71
3 2014-04-30  28295.345  3488.8352      66
4 2014-05-31  23648.287  2738.7096      69

### Monthly KPIs

Monthly aggregation enables trend analysis and supports time-based dashboard visuals.

In [56]:
category_kpis = df.groupby('category').agg({
    'sales':'sum',
    'profit':'sum',
    'order_id':'nunique'
}).sort_values(by='sales',ascending =False).reset_index()

category_kpis.rename(columns={'order_id':'orders'},inplace=True)

category_kpis

          category        sales       profit  orders
0       Technology  836154.0330  145454.9481    1544
1        Furniture  741999.7953   18451.2728    1764
2  Office Supplies  719047.0320  122490.8008    3742

### Catregory Performance

Identifies top-performing categories and their contribution to revenue and profit.

In [57]:
regional_kpis = df.groupby('region').agg({
    'sales':'sum',
    'profit':'sum',
    'order_id':'nunique'
}).sort_values(by='sales',ascending =False).reset_index()

regional_kpis.rename(columns={'order_id':'orders'},inplace=True)

regional_kpis

    region        sales       profit  orders
0     West  725457.8245  108418.4489    1611
1     East  678781.2400   91522.7800    1401
2  Central  501239.8908   39706.3625    1175
3    South  391721.9050   46749.4303     822

### Regional Performance

Highlights geographic differences in sales and profit

In [58]:
product_kpis = df.groupby('product_name').agg({
    'sales':'sum',
    'profit':'sum'
}).sort_values(by='sales',ascending =False).reset_index()


product_kpis.head(10)

                                        product_name      sales        profit
0              Canon imageCLASS 2200 Advanced Copier  61599.824  2.519993e+04
1  Fellowes PB500 Electric Punch Plastic Comb Bin...  27453.384  7.753039e+03
2  Cisco TelePresence System EX90 Videoconferenci...  22638.480 -1.811078e+03
3       HON 5400 Series Task Chairs for Big and Tall  21870.576  5.684342e-14
4         GBC DocuBind TL300 Electric Binding System  19823.479  2.233505e+03
5   GBC Ibimaster 500 Manual ProClick Binding System  19024.500  7.609800e+02
6               Hewlett Packard LaserJet 3310 Copier  18839.686  6.983884e+03
7  HP Designjet T520 Inkjet Large Format Printer ...  18374.895  4.094977e+03
8          GBC DocuBind P400 Electric Binding System  17965.068 -1.878166e+03
9        High Speed Automatic Electric Letter Opener  17030.312 -2.620048e+02

### Product Performance

Identifies high-performing and under-performing products.

In [59]:
discount_kpis = df.groupby('discount').agg({
    'sales':'sum',
    'profit':'sum'
}).reset_index()

discount_kpis

    discount         sales       profit
0       0.00  1.087908e+06  320987.6032
1       0.10  5.436935e+04    9029.1770
2       0.15  2.755852e+04    1418.9915
3       0.20  7.645944e+05   90337.3060
4       0.30  1.032267e+05  -10369.2774
5       0.32  1.449346e+04   -2391.1377
6       0.40  1.164178e+05  -23057.0504
7       0.45  5.484974e+03   -2493.1111
8       0.50  5.891854e+04  -20506.4281
9       0.60  6.644700e+03   -5944.6552
10      0.70  4.062028e+04  -40075.3569
11      0.80  1.696376e+04  -30539.0392

### Discount Impact

Analysis shows that higher discounts often reducs profitability.

This insight suggests that discount strategies should be carefully controlled.

In [60]:
customer_kpis = df.groupby('customer_id').agg({
    'sales':'sum',
    'order_id':'nunique'
}).rename(columns={'order_id':'orders'})

customer_kpis

                sales  orders
customer_id
AA-10315     5563.560       5
AA-10375     1056.390       9
AA-10480     1790.512       4
AA-10645     5086.935       6
AB-10015      886.156       3
...               ...     ...
XP-21865     2374.658      11
YC-21895     5454.350       5
YS-21880     6720.444       8
ZC-21910     8025.707      13
ZD-21925     1493.944       5

[793 rows x 2 columns]

### Customer Behaviour

Customer-level metrics help identify high-value customers and purchasing patterns.

In [61]:
df.head()

,row_id,order_id,order_date,ship_date,ship_mode,customer_id,customer_name,segment,country,city,...,sub_category,product_name,sales,quantity,discount,profit,year,month,month_name,profit_margin
0,1,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136,2016,11,Nov,0.1600
1,2,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820,2016,11,Nov,0.3000
2,3,CA-2016-138688,2016-06-12,2016-06-16,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714,2016,6,Jun,0.4700
3,4,US-2015-108966,2015-10-11,2015-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310,2015,10,Oct,-0.4000
4,5,US-2015-108966,2015-10-11,2015-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164,2015,10,Oct,0.1125

In [62]:
df.to_csv("../data/processed/dashboard_data.csv", index =False)
monthly_kpis.to_csv("../data/processed/monthly_kpis.csv",index=False)
category_kpis.to_csv("../data/processed/category_kpis.csv",index=False)
regional_kpis.to_csv("../data/processed/regional_kpis.csv",index=False)
product_kpis.to_csv("../data/processed/product_kpis.csv",index=False)
discount_kpis.to_csv("../data/processed/discount_kpis.csv",index=False)
customer_kpis.to_csv("../data/processed/customer_kpis.csv",index=False)

In [63]:
kpi_summary = pd.DataFrame({
    'total_sales':[df['sales'].sum()],
    'total_profit':[df['profit'].sum()],
    'total_orders':[df['order_id'].nunique()],
    'avg_order_value':[df.groupby('order_id')['sales'].sum().mean()],
    'avg_profit_margin':[(df['profit']/df['sales']).mean()]
                         })
kpi_summary.to_csv("../data/processed/kpi_summary.csv", index=False)

### KPI Summary

The following key metrics were developed:

- Total Sales, Profit, Orders, Quantity
- Profit Margin
- Average Order Value
- Monthly Performance Trends
- Category and regional breakdowns
- Discount impact on profitability

These KPIs form the foundation of the sales dashboard.